config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  get 'categories/index'
  get 'categories/show'

  resources :products
  resources :offers, only: %i[create update]
  resources :categories, only: %i[index show], defaults: { format: :json }

  get 'users/:user_id/offers', to: 'offers#index', as: 'user_offers'

  get 'profiles', to: 'profiles#show'
  put 'profiles', to: 'profiles#update'

  resources :notifications, only: %[index] do
    put '/read', to: 'notifications#read', on: :member
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "users", to: "devise/sessions#new"
  end

  root 'home#index'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many   :offers, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true, numericality: { positive: true }
  validates :description, presence: true

  enum status: {
    draft: 'DRAFT',
    published: 'PUBLISHED',
  }

  def price_in_format
    "Rp #{price.to_i.to_fs(:delimited, delimiter: '.')}"
  end

  def notify_user
    notification = Notification.new(subject: 'Berhasil di terbitkan', body: "#{name}<br>#{price_in_format}",
                                    click_action: Rails.application.routes.url_helpers.product_path(id), user:)

    unless notification.save
      self.errors = notification.errors
      return false
    end

    notification.image.attach(images.first.blob) if images.attached?

    true
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :block_if_profile_blank!, only: %i[new create edit update destroy]
  before_action :verify_ownership, only: %i[edit update destroy]

  layout 'full'

  # GET /products or /products.json
  def index
    @products = Product.includes(:category).with_attached_images.published.paginate(page: params[:page].present? ? params[:page] : 1, per_page: 10)
    @products = @products.all if params[:product].try(:[], :category_id).blank?
    @products = @products.where(filter_params) if params[:product].present?

    respond_to do |format|
      format.html do
        authenticate_user!
        @products = @products.where(user: current_user)
      end

      format.json do
        @products = @products.includes(user: :city)

        if user_signed_in? && params[:user_id].present?
          @products = @products.where(user: current_user)
        end
      end
    end
  end

  # GET /products/1 or /products/1.json
  def show
    @offer = Offer.new unless mine?
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @product.save
        @product.notify_user if @product.published?

        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product.images.each do |image|
      image.purge unless update_product_params[:persisted_images].include?(image.signed_id)
    end

    respond_to do |format|
      if @product.update(update_product_params.except(:persisted_images, :images))
        @product.notify_user if @product.status_previously_changed? && @product.published?
        @product.images.attach(update_product_params[:images])

        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.with_attached_images.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :description, :category_id, :status, images: [])
  end

  def update_product_params
    params.require(:product).permit(:name, :price, :description, :category_id, :status, images: [], persisted_images: [])
  end

  def filter_params
    params.require(:product).permit(:sold, :liked)
  end

  def verify_ownership
    return if mine?

    respond_to do |format|
      format.html { redirect_to products_url, status: :forbidden }
      format.json { render json: { "user_id": ["doesn't have the right to do this action"] }, status: :forbidden }
    end
  end

  def mine?
    user_signed_in? && @product.user_id.eql?(current_user.id)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def mine?
    return false if current_user.blank?

    @product.user_id.eql?(current_user.id)
  end

  def offered?
    return false if current_user.blank?

    @product.offers.where(from_id: current_user.id, status: :initiated).exists?
  end

  def purchased?
    return false if current_user.blank?

    @product.offers.where(from_id: current_user.id, status: :finished).exists?
  end

  def published?
    @product.published?
  end

  def all_products?
    params[:product].nil?
  end

  def liked_product?
    params[:product].present? && params[:product][:liked].eql?('true') && params[:product][:sold].eql?('false')
  end

  def sold_product?
    params[:product].present? && params[:product][:sold].eql?('true')
  end

  def all_product_class(classes)
    classes += ' active' if all_products?
    classes
  end

  def liked_product_class(classes)
    classes += ' active' if liked_product?
    classes
  end

  def sold_product_class(classes)
    classes += ' active' if sold_product?
    classes
  end
end

app/views/products/_form.html.erb
<section class="row mt-5">
  <div class="col-11">
    <%= form_with(model: product, html: { multipart: true }) do |form| %>
      <div class="mb-4">
        <%= form.label :name, "Nama Produk", style: "display: block", class: "form-label" %>
        <%= form.text_field :name, class: "form-control rounded-4 p-3", placeholder: "Nama Produk", required: true %>
        <% if product.errors.any? { |error| error.attribute.eql?(:name) } %>
          <div class="form-text text-danger">
            <%= product.errors.detect { |error| error.attribute.eql?(:name) }.full_message %>
          </div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :price, "Harga Produk", style: "display: block", class: "form-label" %>
        <%= form.number_field :price, class: "form-control rounded-4 p-3", placeholder: "Rp 0,00", required: true %>
        <% if product.errors.any? { |error| error.attribute.eql?(:price) } %>
          <div class="form-text text-danger">
            <%= product.errors.detect { |error| error.attribute.eql?(:price) }.full_message %>
          </div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :category_id, "Kategori", style: "display: block", class: "form-label" %>
        <%= form.collection_select :category_id, Category.all, :id, :name, { include_blank: "Pilih Kategori" }, class: "form-select rounded-4 p-3", required: true %>
        <% if product.errors.any? { |error| error.attribute.eql?(:category) } %>
          <div class="form-text text-danger">
            <%= product.errors.detect { |error| error.attribute.eql?(:category) }.full_message %>
          </div>
        <% end %>
      </div>

      <div class="mb-4">
        <%= form.label :description, "Deskripsi", style: "display: block", class: "form-label" %>
        <%= form.text_area :description, class: "form-control rounded-4 p-3", placeholder: "Contoh: Jalan Ikan Hiu 33", required: true %>
        <% if product.errors.any? { |error| error.attribute.eql?(:description) } %>
          <div class="form-text text-danger">
            <%= product.errors.detect { |error| error.attribute.eql?(:description) }.full_message %>
          </div>
        <% end %>
      </div>

      <div class="mb-4 input-images gap-4" id="input-images">
        <% if form.object.persisted? %>
          <% form.object.images.each do |image| %>
            <div class="form-image-preview position-relative rounded-4 overflow-hidden">
              <%= image_tag image.representation(resize_to_limit: [480, 480]), class: "img-preview" %>
              <button type="button" onclick="this.parentElement.remove()" class="btn-close btn-close-white position-absolute top-0 start-100 translate-middle" aria-label="close" style="transform: translate(-150%, 50%) !important"></button>
              <%= form.hidden_field :persisted_images, multiple: true, value: image.signed_id %>
            </div>
          <% end %>
        <% end %>

        <%= render "components/input/image", form: form, name: :images %>
      </div>

      <div class="mb-4 d-flex gap-5">
        <%= form.radio_button :status, "draft", class: "btn-check", autocomplete: "off", onchange: "this.form.submit()", checked: false %>
        <%= form.label :status_draft, "Preview", class: "btn btn-outline-primary w-50 rounded-4 p-3" %>

        <%= form.radio_button :status, "published", class: "btn-check", autocomplete: "off", onchange: "this.form.submit()", checked: false %>
        <%= form.label :status_published, "Terbitkan", class: "btn btn-primary w-50 rounded-4 p-3" %>
      </div>
    <% end %>
  </div>
</section>

<!-- TODO: Use rails javascript integration -->
<script>
  function clickFileInput(element) {
    const input = element.nextElementSibling.nextElementSibling
    input.previousFiles = input.files;
    input.addEventListener('change', onImageInputElementChanged)

    input.click();
  }

  function onImageInputElementChanged(e) {
    if (e.target.files.length === 0) return;

    const dt = new DataTransfer();

    for (const file of e.target.previousFiles) {
      dt.items.add(file);
    }

    for (const file of e.target.files) {
      let div = document.createElement('div');
      div.classList.add('form-image-preview', 'position-relative', 'rounded-4', 'overflow-hidden');

      let img = document.createElement('img');
      img.classList.add("img-preview");
      img.src = URL.createObjectURL(file);

      let button = document.createElement('button');
      button.type = 'button';
      button.ariaLabel = 'close';
      button.style = "transform: translate(-150%, 50%) !important";
      button.dataset.inputId = e.target.id;
      button.file = file;
      button.classList.add('btn-close', 'btn-close-white', 'position-absolute', 'top-0', 'start-100', 'translate-middle');
      button.addEventListener('click', onImageInputRemoveButtonClicked)

      div.append(img);
      div.append(button);

      dt.items.add(file);
      e.target.previousElementSibling.previousElementSibling.before(div);
    }

    e.target.previousFiles = null;
    e.target.files = dt.files;
  }

  function onImageInputRemoveButtonClicked(e) {
    const input = document.getElementById(e.target.dataset.inputId);
    const dt = new DataTransfer()

    for (let file of input.files) {
      if (file.name !== e.target.file.name) {
        dt.items.add(file)
      }
    }

    input.files = dt.files;

    e.target.parentElement.remove();
  }
</script>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= product.user_id %>
  </p>

</div>

app/views/products/edit.html.erb
<section class="container container-sm position-relative">
  <%= render "components/buttons/back" %>
  <%= render "form", product: @product %>
</section>

app/views/products/index.html.erb
<div class="container">
  <h3 class="fw-bold my-5">Daftar Jual Saya</h3>

  <div class="card py-2 px-4 rounded-4 border-4 border-light mt-5 d-flex justify-content-between">
    <div class="d-flex align-items-center">
      <% if current_user.avatar.attached? %>
        <%= image_tag current_user.avatar.representation(resize_to_limit: [400, 400]), class: "img-avatar w-100 rounded-4" %>
      <% else %>
        <%= image_tag "/empty-image.svg", class: "img-avatar w-100 rounded-4" %>
      <% end %>

      <div class="py-3 ps-4">
        <div class="fs-5 fw-bold"><%= current_user.name %></div>
        <div class="fs-6 text-black-50"><%= current_user.city.try(:name) %></div>
      </div>

      <%= link_to "Edit" , profiles_path, class: "btn btn-outline-primary rounded-4 px-3 ms-auto" %>
    </div>
  </div>

  <div class="row my-5">
    <div class="col-12 col-lg-3">
      <div class="card border-0 rounded-4 shadow p-4">
        <h5 class="card-title mb-4">Kategori</h5>

        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to products_path, class: all_product_class("nav-link d-flex py-3 border-bottom border-1") do %>
              <i class="bi bi-box me-3"></i>
              <span class="me-auto">Semua Produk</span>
              <i class="bi bi-chevron-right"></i>
            <% end %>

            <%= link_to products_path(product: { sold: false, liked: true }), class: liked_product_class("nav-link d-flex py-3 border-bottom border-1") do %>
              <i class="bi bi-heart me-3"></i>
              <span class="me-auto">Diminati</span>
              <i class="bi bi-chevron-right"></i>
            <% end %>

            <%= link_to products_path(product: { sold: true }), class: sold_product_class("nav-link d-flex py-3") do %>
              <i class="bi bi-currency-dollar me-3"></i>
              <span class="me-auto">Terjual</span>
              <i class="bi bi-chevron-right"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-12 col-lg-9 mt-5 mt-lg-0">
      <div class="row g-4">
        <% if all_products? %>
          <div class="col-12 col-lg-4">
            <%= link_to new_product_path, class: "new-product-button h-100 w-100 border-2 rounded-4 text-black-50 d-flex align-items-center justify-content-center" do %>
              <div class="text-center">
                <i class="bi bi-plus display-3"></i>
                <h5 class="fw-normal fs-6">Tambah Produk</h5>
              </div>
            <% end %>
          </div>
        <% end %>

        <% if @products.any? %>
          <% @products.each do |product| %>
            <div class="col-12 col-lg-4">
              <%= render "components/product", product: product %>
            </div>
          <% end %>

          <%= will_paginate @products, page_links: false, class: "d-flex gap-4 align-items-center justify-content-center my-5" %>
        <% elsif !all_products? %>
          <div class="d-flex flex-column justify-content-center align-items-center">
            <div class="container d-flex flex-column justify-content-center align-items-center">
              <%= image_tag "/empty-product.svg", class: "img-fluid" %>
              <p class="py-5">Belum ada produkmu yang diminati nih, sabar ya rejeki nggak kemana kok</p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<section class="container container-sm position-relative">
  <%= render "components/buttons/back" %>
  <%= render "form", product: @product %>
</section>

app/views/products/show.html.erb
<section class="container my-5">
  <div class="row">
    <div class="col-8">
      <% if @product.images.attached? %>
        <div id="productImage" class="carousel slide w-100 rounded-4 overflow-hidden carousel-fade" data-bs-ride="carousel">
          <% if @product.images.size > 1 %>
            <div class="carousel-indicators">
              <% @product.images.each_with_index do |image, index| %>
                <button type="button" data-bs-target="#productImage" data-bs-slide-to="<%= index %>" class="<%= index.zero? ? "active" : "" %>" aria-current="<%= index.zero? ? "active" : "" %>" aria-label="Slide <%= index + 1 %>"></button>
              <% end %>
            </div>
          <% end %>

          <div class="carousel-inner">
            <% @product.images.each_with_index do |image, index| %>
              <div class="carousel-item <%= index.zero? ? "active" : "" %>">
                <%= image_tag image.representation(resize_to_limit: [1024, 1024]), class: "w-100" %>
              </div>
            <% end %>
          </div>

          <% if @product.images.size > 1 %>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          <% end %>
        </div>
      <% end %>

      <div class="card mt-5 p-2 border border-4 border-light rounded-4">
        <div class="card-body">
          <h5 class="card-title fs-6">Deskripsi</h5>
          <p class="card-text text-black-50 fs-6"><%= @product.description %></p>
        </div>
      </div>

    </div>

    <div class="col-4">
      <div class="card p-2 rounded-4 shadow border-0">
        <div class="card-body">
          <h5 class="card-title fs-5 fw-bolder"><%= @product.name %></h5>
          <p class="card-text text-black-50 fs-6"><%= @product.category.name %></p>
          <p class="card-text fs-5">Rp <%= number_with_delimiter(@product.price.to_i, delimiter: ".") %></p>
          <% if mine? %>
            <% unless published? %>
              <%= form_with model: @product, method: "PUT" do |form| %>
                <%= form.hidden_field :status, value: "published" %>
                <%= form.submit "Terbitkan", class: "btn btn-lg btn-primary fs-6 rounded-4 w-100 mb-3 py-3 fw-bold" %>
              <% end %>
            <% end %>
            <%= link_to "Edit", edit_product_path(@product.id), class: "btn btn-lg btn-outline-primary fs-6 rounded-4 w-100 py-3 fw-bold" %>
            <%= link_to "Delete", product_path(@product.id), data: { turbo_method: :delete }, class: "btn btn-lg btn-danger fs-6 rounded-4 w-100 py-3 fw-bold mt-3" %>
          <% elsif offered? %>
            <button class="btn btn-lg btn-primary fs-6 rounded-4 w-100 mb-3 py-3 fw-bold disabled">Menunggu respon penjual</button>
          <% elsif purchased? %>
            <button class="btn btn-lg btn-primary fs-6 rounded-4 w-100 mb-3 py-3 fw-bold disabled">Terbeli</button>
          <% else %>
            <button class="btn btn-lg btn-primary fs-6 rounded-4 w-100 mb-3 py-3 fw-bold" data-bs-toggle="modal" data-bs-target="#offerModal">Saya tertarik dan ingin nego</button>
          <% end %>
        </div>
      </div>

      <div class="card py-2 px-4 rounded-4 shadow border-0 mt-5">
        <div class="d-flex align-items-center">
          <%= image_tag @product.user.avatar.representation(resize_to_limit: [400, 400]), class: "img-avatar w-100 rounded-4" %>

          <div class="card-body">
            <div class="fs-5 fw-bold"><%= @product.user.name %></div>
            <div class="fs-6 text-black-50"><%= @product.user.city.try(:name) %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<% unless mine? %>
  <div class="modal" tabindex="-1" id="offerModal">
    <div class="modal-dialog modal-dialog-centered">
      <%= form_with model: @offer, class: "modal-content px-4 py-2" do |form| %>
        <%= form.hidden_field :product_id, value: @product.id %>
        <%= form.hidden_field :to_id, value: @product.user_id %>

        <div class="modal-header border-0">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h5 class="fs-5 fw-bold mb-3">Masukkan Harga Tawarmu</h5>
          <p class="text-black-50 fs-5">Harga tawaranmu akan diketahui penual, jika penjual cocok kamu akan segera dihubungi penjual.</p>
          <div class="card bg-light border-0 rounded-4 shadow-sm px-4 py-2 mb-4">
            <div class="d-flex align-items-center">
              <%= image_tag @product.images.first.representation(resize_to_limit: [400, 400]), class: "img-offer w-100 rounded-4" %>

              <div class="card-body">
                <div class="fs-5 fw-bold"><%= @product.name %></div>
                <div class="fs-6"><%= to_price(@product.price) %></div>
              </div>
            </div>
          </div>
          <div class="mb-4">
            <%= form.label :price, "Harga Tawar", style: "display: block", class: "form-label" %>
            <%= form.number_field :price, class: "form-control rounded-4 p-3", placeholder: "Rp 0,00" %> 
          </div>
        </div>
        <div class="modal-footer border-0">
          <%= form.submit "Kirim", class: "btn btn-primary p-3 w-100 rounded-4 fw-bold" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>